---
name: Build & Test
description: Build the final container image and run tests on it

inputs:
  registry:
    description: Target registry to push the final image.
    default: "localhost:5000"
  namespace:
    description: Namespace of the container image.
    default: ansible
  final_image:
    description: Name of the final image.
    default: ansible-workspace-env-reference
  publish:
    description: Publish the image to ghcr.io
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare
      shell: bash
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # network=host driver-opt needed to push to local registry
        driver-opts: network=host
        buildkitd-flags: --debug

    - name: Build final image
      id: build-final
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}/devspaces/context
        provenance: false
        file: ${{ github.workspace }}/devspaces/Containerfile
        load: true
        tags: |
          ${{ inputs.namespace }}/${{ inputs.final_image }}:test
        # cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
        # cache-to: type=gha,scope=build-${{ env.PLATFORM_PAIR }}

    - name: Docker meta
      id: meta
      if: ${{ inputs.publish == 'true' }}
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ inputs.namespace }}/${{ inputs.final_image }}
        flavor: |
          latest=false
        tags: |
          type=raw,value=latest
          type=ref,event=tag

    - name: Push the built image to ghcr.io
      id: push-final
      if: ${{ inputs.publish == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}/devspaces/context
        provenance: false
        file: ${{ github.workspace }}/devspaces/Containerfile
        tags: ${{ steps.meta.outputs.tags }}
        push: true
